name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - test/test

jobs:
  deploy_ipfs:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    env:
      REACT_APP_SUPPORTED_ETHEREUM_NETWORKS: 'kovan,mumbai,fuji,mainnet,polygon,avalanche'
      REACT_APP_DEFAULT_ETHEREUM_NETWORK: 'mainnet'
      REACT_APP_ENABLE_CACHING_BACKEND: 'true'
      REACT_APP_ENABLE_NASH: 'true'
      REACT_APP_RATES_HISTORY_ENDPOINT: 'https://aave-api-v2.aave.com/data/rates-history'
      NGINX_MODE: 'staging'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: Build and pinata upload
        id: deploy
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_KEY: ${{ secrets.PINATA_SECRET_KEY }}
          PIN_ALIAS: "${{ format('pull_request_{0}', github.head_ref) }}"
        run: npm run build-ipfs

      #- uses: actions/github-script@v5
      #  with:
      #    script: |
      #      github.rest.issues.createComment({
      #        issue_number: context.payload.number,
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        body: 'Preview link: ${{steps.deploy.outputs.uri}}'
      #      })

      - name: test
        uses: djp3/puppeteer-headful@master
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          DOMAIN: 'http://localhost:5000'
          TENDERLY_ACCOUNT: ${{ secrets.TENDERLY_ACCOUNT }}
          TENDERLY_KEY: ${{ secrets.TENDERLY_KEY }}
          TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
        run: cd tests && npm ci && npm run ci
